version: "3.8"
services:
  app:
    image: final_project:v5
    build: .
    container_name: final_project
    volumes:
      - ./:/final_project
    environment:
      - name=value
    ports:
      - "3002:3002"
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=seher
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=seher
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  mysql:
    image: mysql:latest
    ports:
      - "3310:3306"  # Changed this line
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=adalovelaceakademi
      - MYSQL_USER=seher
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network

  redis:
    container_name: redis_db
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  mongo-data:
    driver: local
  mysql-data:
    driver: local

networks:
  my_network:
    driver: bridge